
name: 'cko_dbt_am'
version: '1.0.0'
config-version: 2

profile: 'cko_test_snowflake_db'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models

models:
  cko_dbt_am:
        materialized: view
